version: "1.0"
info:
  model: int-scaffold
packages:
- name: Ser_azpp_ghProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: AddIntsPackage
  gitServerName: srcCtrl_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/AddIntsPackage/_git
  gitUsername: ArtiKhare
  gitBranch: master
- name: upperfspackage
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
